const Constant = {
    apiUrl: 'http://127.0.0.1:8000/api/'
}

export const genre = [
        "4 - Koma",
        "Action",
        "Adventure",
        "Comedy",
        "Cooking",
        "Demons",
        "Drama",
        "Ecchi",
        "Fantasy",
        "Game",
        "Gender Bender",
        "Harem",
        "Historical",
        "Horror",
        "Isekai",
        "Josei",
        "Magic",
        "Martial Art",
        "Martial Arts",
        "Mature",
        "Mecha",
        "Medical",
        "Military",
        "Music",
        "Mystery",
        "Police",
        "Psychological",
        "Reincarnation",
        "Romance",
        "School",
        "School Life",
        "Sci - Fi",
        "Seinen",
        "Shoujo",
        "Shoujo Ai",
        "Shounen",
        "Shounen Ai",
        "Slice of Life",
        "Sports",
        "Super Power",
        "Supernatural",
        "Thriller",
        "Tragedy",
        "Vampire",
        "Webtoons",
        "Yuri",
    ];

export default Constant;